stages:
- run test
- deploy

run_test:
  stage: run test
  image: golang:1.18-stretch
  script:
    - go test -v

deploy:
  stage: deploy
  image: ubuntu:20.04
  before_script:
    - apt update && apt install curl -y
    - curl -fsSL https://railway.app/install.sh | sh
  script:
    - railway up
